name: infobits_pluto
description: Pluto is a simple to use logging tool.
version: 0.0.1
homepage: "https://infobits.dk"
repository: https://github.com/infobits-code/flutter_infobits_pluto

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  stack_trace: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: